<?php
// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/assessments.php');
	include_once(__DIR__ . '/assessments_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('assessments');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'assessments';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`assessments`.`id`" => "id",
		"IF(    CHAR_LENGTH(`classes1`.`class`) || CHAR_LENGTH(`enrollment1`.`term`), CONCAT_WS('',   `classes1`.`class`, '-', `enrollment1`.`term`), '') /* Class */" => "class",
		"`assessments`.`total_marks`" => "total_marks",
		"IF(    CHAR_LENGTH(`staff1`.`full_name`), CONCAT_WS('',   `staff1`.`full_name`), '') /* Teacher */" => "teacher",
		"IF(    CHAR_LENGTH(`subjects1`.`subject`), CONCAT_WS('',   `subjects1`.`subject`), '') /* Result */" => "subject",
		"`assessments`.`avg_performance`" => "avg_performance",
		"`assessments`.`highest_mark`" => "highest_mark",
		"`assessments`.`lowest_mark`" => "lowest_mark",
		"if(`assessments`.`date`,date_format(`assessments`.`date`,'%m/%d/%Y'),'')" => "date",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`assessments`.`id`',
		2 => 2,
		3 => '`assessments`.`total_marks`',
		4 => '`staff1`.`full_name`',
		5 => '`subjects1`.`subject`',
		6 => 6,
		7 => 7,
		8 => 8,
		9 => '`assessments`.`date`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`assessments`.`id`" => "id",
		"IF(    CHAR_LENGTH(`classes1`.`class`) || CHAR_LENGTH(`enrollment1`.`term`), CONCAT_WS('',   `classes1`.`class`, '-', `enrollment1`.`term`), '') /* Class */" => "class",
		"`assessments`.`total_marks`" => "total_marks",
		"IF(    CHAR_LENGTH(`staff1`.`full_name`), CONCAT_WS('',   `staff1`.`full_name`), '') /* Teacher */" => "teacher",
		"IF(    CHAR_LENGTH(`subjects1`.`subject`), CONCAT_WS('',   `subjects1`.`subject`), '') /* Result */" => "subject",
		"`assessments`.`avg_performance`" => "avg_performance",
		"`assessments`.`highest_mark`" => "highest_mark",
		"`assessments`.`lowest_mark`" => "lowest_mark",
		"if(`assessments`.`date`,date_format(`assessments`.`date`,'%m/%d/%Y'),'')" => "date",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`assessments`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`classes1`.`class`) || CHAR_LENGTH(`enrollment1`.`term`), CONCAT_WS('',   `classes1`.`class`, '-', `enrollment1`.`term`), '') /* Class */" => "Class",
		"`assessments`.`total_marks`" => "Total marks",
		"IF(    CHAR_LENGTH(`staff1`.`full_name`), CONCAT_WS('',   `staff1`.`full_name`), '') /* Teacher */" => "Teacher",
		"IF(    CHAR_LENGTH(`subjects1`.`subject`), CONCAT_WS('',   `subjects1`.`subject`), '') /* Result */" => "Result",
		"`assessments`.`avg_performance`" => "Avg performance",
		"`assessments`.`highest_mark`" => "Highest mark",
		"`assessments`.`lowest_mark`" => "Lowest mark",
		"`assessments`.`date`" => "Date",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`assessments`.`id`" => "id",
		"IF(    CHAR_LENGTH(`classes1`.`class`) || CHAR_LENGTH(`enrollment1`.`term`), CONCAT_WS('',   `classes1`.`class`, '-', `enrollment1`.`term`), '') /* Class */" => "class",
		"`assessments`.`total_marks`" => "total_marks",
		"IF(    CHAR_LENGTH(`staff1`.`full_name`), CONCAT_WS('',   `staff1`.`full_name`), '') /* Teacher */" => "teacher",
		"IF(    CHAR_LENGTH(`subjects1`.`subject`), CONCAT_WS('',   `subjects1`.`subject`), '') /* Result */" => "subject",
		"`assessments`.`avg_performance`" => "avg_performance",
		"`assessments`.`highest_mark`" => "highest_mark",
		"`assessments`.`lowest_mark`" => "lowest_mark",
		"if(`assessments`.`date`,date_format(`assessments`.`date`,'%m/%d/%Y'),'')" => "date",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['class' => 'Class', 'teacher' => 'Teacher', 'subject' => 'Result', ];

	$x->QueryFrom = "`assessments` LEFT JOIN `enrollment` as enrollment1 ON `enrollment1`.`stid`=`assessments`.`class` LEFT JOIN `classes` as classes1 ON `classes1`.`id`=`enrollment1`.`class` LEFT JOIN `staff` as staff1 ON `staff1`.`id`=`assessments`.`teacher` LEFT JOIN `subjects` as subjects1 ON `subjects1`.`sub_id`=`assessments`.`subject` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'assessments_view.php';
	$x->TableTitle = 'Assessments';
	$x->TableIcon = 'resources/table_icons/document_prepare.png';
	$x->PrimaryKey = '`assessments`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Class', 'Total marks', 'Teacher', 'Result', 'Avg performance', 'Highest mark', 'Lowest mark', 'Date', ];
	$x->ColFieldName = ['class', 'total_marks', 'teacher', 'subject', 'avg_performance', 'highest_mark', 'lowest_mark', 'date', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/assessments_templateTV.html';
	$x->SelectedTemplate = 'templates/assessments_templateTVS.html';
	$x->TemplateDV = 'templates/assessments_templateDV.html';
	$x->TemplateDVP = 'templates/assessments_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: assessments_init
	$render = true;
	if(function_exists('assessments_init')) {
		$args = [];
		$render = assessments_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: assessments_header
	$headerCode = '';
	if(function_exists('assessments_header')) {
		$args = [];
		$headerCode = assessments_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: assessments_footer
	$footerCode = '';
	if(function_exists('assessments_footer')) {
		$args = [];
		$footerCode = assessments_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
