<?php
// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/class_notes.php');
	include_once(__DIR__ . '/class_notes_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('class_notes');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'class_notes';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`class_notes`.`id`" => "id",
		"IF(    CHAR_LENGTH(`subjects1`.`subject`), CONCAT_WS('',   `subjects1`.`subject`), '') /* Subject */" => "subject",
		"IF(    CHAR_LENGTH(`classes1`.`class`), CONCAT_WS('',   `classes1`.`class`), '') /* Class */" => "class",
		"`class_notes`.`term`" => "term",
		"`class_notes`.`topics`" => "topics",
		"`class_notes`.`resource`" => "resource",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`class_notes`.`id`',
		2 => '`subjects1`.`subject`',
		3 => '`classes1`.`class`',
		4 => 4,
		5 => 5,
		6 => 6,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`class_notes`.`id`" => "id",
		"IF(    CHAR_LENGTH(`subjects1`.`subject`), CONCAT_WS('',   `subjects1`.`subject`), '') /* Subject */" => "subject",
		"IF(    CHAR_LENGTH(`classes1`.`class`), CONCAT_WS('',   `classes1`.`class`), '') /* Class */" => "class",
		"`class_notes`.`term`" => "term",
		"`class_notes`.`topics`" => "topics",
		"`class_notes`.`resource`" => "resource",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`class_notes`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`subjects1`.`subject`), CONCAT_WS('',   `subjects1`.`subject`), '') /* Subject */" => "Subject",
		"IF(    CHAR_LENGTH(`classes1`.`class`), CONCAT_WS('',   `classes1`.`class`), '') /* Class */" => "Class",
		"`class_notes`.`term`" => "Term",
		"`class_notes`.`topics`" => "Topics",
		"`class_notes`.`resource`" => "Resource",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`class_notes`.`id`" => "id",
		"IF(    CHAR_LENGTH(`subjects1`.`subject`), CONCAT_WS('',   `subjects1`.`subject`), '') /* Subject */" => "subject",
		"IF(    CHAR_LENGTH(`classes1`.`class`), CONCAT_WS('',   `classes1`.`class`), '') /* Class */" => "class",
		"`class_notes`.`term`" => "term",
		"`class_notes`.`topics`" => "topics",
		"`class_notes`.`resource`" => "resource",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['subject' => 'Subject', 'class' => 'Class', ];

	$x->QueryFrom = "`class_notes` LEFT JOIN `subjects` as subjects1 ON `subjects1`.`sub_id`=`class_notes`.`subject` LEFT JOIN `classes` as classes1 ON `classes1`.`id`=`class_notes`.`class` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'class_notes_view.php';
	$x->TableTitle = 'Class notes';
	$x->TableIcon = 'resources/table_icons/books.png';
	$x->PrimaryKey = '`class_notes`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Subject', 'Class', 'Term', 'Topics', 'Resource', ];
	$x->ColFieldName = ['subject', 'class', 'term', 'topics', 'resource', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/class_notes_templateTV.html';
	$x->SelectedTemplate = 'templates/class_notes_templateTVS.html';
	$x->TemplateDV = 'templates/class_notes_templateDV.html';
	$x->TemplateDVP = 'templates/class_notes_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: class_notes_init
	$render = true;
	if(function_exists('class_notes_init')) {
		$args = [];
		$render = class_notes_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: class_notes_header
	$headerCode = '';
	if(function_exists('class_notes_header')) {
		$args = [];
		$headerCode = class_notes_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: class_notes_footer
	$footerCode = '';
	if(function_exists('class_notes_footer')) {
		$args = [];
		$footerCode = class_notes_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
