<?php
// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/classes.php');
	include_once(__DIR__ . '/classes_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('classes');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'classes';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`classes`.`id`" => "id",
		"`classes`.`class`" => "class",
		"`classes`.`year`" => "year",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`classes`.`id`',
		2 => 2,
		3 => '`classes`.`year`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`classes`.`id`" => "id",
		"`classes`.`class`" => "class",
		"`classes`.`year`" => "year",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`classes`.`id`" => "ID",
		"`classes`.`class`" => "Class",
		"`classes`.`year`" => "Year",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`classes`.`id`" => "id",
		"`classes`.`class`" => "class",
		"`classes`.`year`" => "year",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`classes` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'classes_view.php';
	$x->TableTitle = 'Classes';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`classes`.`id`';
	$x->DefaultSortField = '3';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['Class', 'Year', ];
	$x->ColFieldName = ['class', 'year', ];
	$x->ColNumber  = [2, 3, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/classes_templateTV.html';
	$x->SelectedTemplate = 'templates/classes_templateTVS.html';
	$x->TemplateDV = 'templates/classes_templateDV.html';
	$x->TemplateDVP = 'templates/classes_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: classes_init
	$render = true;
	if(function_exists('classes_init')) {
		$args = [];
		$render = classes_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: classes_header
	$headerCode = '';
	if(function_exists('classes_header')) {
		$args = [];
		$headerCode = classes_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: classes_footer
	$footerCode = '';
	if(function_exists('classes_footer')) {
		$args = [];
		$footerCode = classes_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
