<?php
// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/clearance_tickets.php');
	include_once(__DIR__ . '/clearance_tickets_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('clearance_tickets');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'clearance_tickets';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`clearance_tickets`.`c_id`" => "c_id",
		"if(`clearance_tickets`.`date`,date_format(`clearance_tickets`.`date`,'%m/%d/%Y'),'')" => "date",
		"`clearance_tickets`.`full_name`" => "full_name",
		"`clearance_tickets`.`class`" => "class",
		"`clearance_tickets`.`term`" => "term",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`clearance_tickets`.`c_id`',
		2 => '`clearance_tickets`.`date`',
		3 => 3,
		4 => 4,
		5 => 5,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`clearance_tickets`.`c_id`" => "c_id",
		"if(`clearance_tickets`.`date`,date_format(`clearance_tickets`.`date`,'%m/%d/%Y'),'')" => "date",
		"`clearance_tickets`.`full_name`" => "full_name",
		"`clearance_tickets`.`class`" => "class",
		"`clearance_tickets`.`term`" => "term",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`clearance_tickets`.`c_id`" => "Clearance ID",
		"`clearance_tickets`.`date`" => "Date",
		"`clearance_tickets`.`full_name`" => "Full name",
		"`clearance_tickets`.`class`" => "Class",
		"`clearance_tickets`.`term`" => "Term",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`clearance_tickets`.`c_id`" => "c_id",
		"if(`clearance_tickets`.`date`,date_format(`clearance_tickets`.`date`,'%m/%d/%Y'),'')" => "date",
		"`clearance_tickets`.`full_name`" => "full_name",
		"`clearance_tickets`.`class`" => "class",
		"`clearance_tickets`.`term`" => "term",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`clearance_tickets` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'clearance_tickets_view.php';
	$x->TableTitle = 'Clearance tickets';
	$x->TableIcon = 'resources/table_icons/tick.png';
	$x->PrimaryKey = '`clearance_tickets`.`c_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Clearance ID', 'Date', 'Full name', 'Class', 'Term', ];
	$x->ColFieldName = ['c_id', 'date', 'full_name', 'class', 'term', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/clearance_tickets_templateTV.html';
	$x->SelectedTemplate = 'templates/clearance_tickets_templateTVS.html';
	$x->TemplateDV = 'templates/clearance_tickets_templateDV.html';
	$x->TemplateDVP = 'templates/clearance_tickets_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "col-lg-4";
	$x->DVClasses = "col-lg-8";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: clearance_tickets_init
	$render = true;
	if(function_exists('clearance_tickets_init')) {
		$args = [];
		$render = clearance_tickets_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: clearance_tickets_header
	$headerCode = '';
	if(function_exists('clearance_tickets_header')) {
		$args = [];
		$headerCode = clearance_tickets_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: clearance_tickets_footer
	$footerCode = '';
	if(function_exists('clearance_tickets_footer')) {
		$args = [];
		$footerCode = clearance_tickets_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
