<?php

// Data functions (insert, update, delete, form) for table enrollment

// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

function enrollment_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('enrollment');
	if(!$arrPerm['insert']) return false;

	$data = [
		'date' => Request::dateComponents('date', '1'),
		'full_name' => Request::lookup('full_name', ''),
		'class' => Request::lookup('class', ''),
		'term' => Request::val('term', ''),
		'fees_code' => Request::lookup('fees_code', ''),
	];

	if($data['full_name'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Full name': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['class'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Class': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['term'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Term': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: enrollment_before_insert
	if(function_exists('enrollment_before_insert')) {
		$args = [];
		if(!enrollment_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('enrollment', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	// automatic year if passed as filterer
	if(Request::val('filterer_year')) {
		sql("UPDATE `enrollment` SET `year`='" . makeSafe(Request::val('filterer_year')) . "' WHERE `stid`='" . makeSafe($recID, false) . "'", $eo);
	}

	update_calc_fields('enrollment', $recID, calculated_fields()['enrollment']);

	// hook: enrollment_after_insert
	if(function_exists('enrollment_after_insert')) {
		$res = sql("SELECT * FROM `enrollment` WHERE `stid`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!enrollment_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('enrollment', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) enrollment_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function enrollment_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function enrollment_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('enrollment', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: enrollment_before_delete
	if(function_exists('enrollment_before_delete')) {
		$args = [];
		if(!enrollment_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: fees_payments
	$res = sql("SELECT `stid` FROM `enrollment` WHERE `stid`='{$selected_id}'", $eo);
	$stid = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `fees_payments` WHERE `student`='" . makeSafe($stid[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'fees_payments', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'fees_payments', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'enrollment_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'enrollment_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: assessments
	$res = sql("SELECT `stid` FROM `enrollment` WHERE `stid`='{$selected_id}'", $eo);
	$stid = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `assessments` WHERE `class`='" . makeSafe($stid[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'assessments', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'assessments', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'enrollment_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'enrollment_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: results
	$res = sql("SELECT `stid` FROM `enrollment` WHERE `stid`='{$selected_id}'", $eo);
	$stid = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `results` WHERE `student_name`='" . makeSafe($stid[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'results', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'results', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'enrollment_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'enrollment_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: exams
	$res = sql("SELECT `stid` FROM `enrollment` WHERE `stid`='{$selected_id}'", $eo);
	$stid = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `exams` WHERE `class`='" . makeSafe($stid[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'exams', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'exams', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'enrollment_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'enrollment_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: rizalts
	$res = sql("SELECT `stid` FROM `enrollment` WHERE `stid`='{$selected_id}'", $eo);
	$stid = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `rizalts` WHERE `student_name`='" . makeSafe($stid[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'rizalts', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'rizalts', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'enrollment_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'enrollment_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `enrollment` WHERE `stid`='{$selected_id}'", $eo);

	// hook: enrollment_after_delete
	if(function_exists('enrollment_after_delete')) {
		$args = [];
		enrollment_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='enrollment' AND `pkValue`='{$selected_id}'", $eo);
}

function enrollment_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('enrollment', $selected_id, 'edit')) return false;

	$data = [
		'date' => Request::dateComponents('date', ''),
		'full_name' => Request::lookup('full_name', ''),
		'class' => Request::lookup('class', ''),
		'term' => Request::val('term', ''),
		'fees_code' => Request::lookup('fees_code', ''),
	];

	if($data['full_name'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Full name': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['class'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Class': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['term'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Term': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('enrollment', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: enrollment_before_update
	if(function_exists('enrollment_before_update')) {
		$args = ['old_data' => $old_data];
		if(!enrollment_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'enrollment', 
		backtick_keys_once($set), 
		['`stid`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="enrollment_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('enrollment', $data['selectedID'], calculated_fields()['enrollment']);

	// hook: enrollment_after_update
	if(function_exists('enrollment_after_update')) {
		$res = sql("SELECT * FROM `enrollment` WHERE `stid`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['stid'];
		$args = ['old_data' => $old_data];
		if(!enrollment_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='enrollment' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function enrollment_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('enrollment');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_full_name = Request::val('filterer_full_name');
	$filterer_class = Request::val('filterer_class');
	$filterer_fees_code = Request::val('filterer_fees_code');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: date
	$combo_date = new DateCombo;
	$combo_date->DateFormat = "mdy";
	$combo_date->MinYear = defined('enrollment.date.MinYear') ? constant('enrollment.date.MinYear') : 1900;
	$combo_date->MaxYear = defined('enrollment.date.MaxYear') ? constant('enrollment.date.MaxYear') : 2100;
	$combo_date->DefaultDate = parseMySQLDate('1', '1');
	$combo_date->MonthNames = $Translation['month names'];
	$combo_date->NamePrefix = 'date';
	// combobox: full_name
	$combo_full_name = new DataCombo;
	// combobox: class
	$combo_class = new DataCombo;
	// combobox: term
	$combo_term = new Combo;
	$combo_term->ListType = 2;
	$combo_term->MultipleSeparator = ', ';
	$combo_term->ListBoxHeight = 10;
	$combo_term->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/enrollment.term.csv')) {
		$term_data = addslashes(implode('', @file(__DIR__ . '/hooks/enrollment.term.csv')));
		$combo_term->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($term_data))));
		$combo_term->ListData = $combo_term->ListItem;
	} else {
		$combo_term->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("I;;II;;III"))));
		$combo_term->ListData = $combo_term->ListItem;
	}
	$combo_term->SelectName = 'term';
	$combo_term->AllowNull = false;
	// combobox: fees_code
	$combo_fees_code = new DataCombo;

	if($selected_id) {
		if(!check_record_permission('enrollment', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('enrollment', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('enrollment', $selected_id, 'delete');

		$res = sql("SELECT * FROM `enrollment` WHERE `stid`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'enrollment_view.php', false);
		}
		$combo_date->DefaultDate = $row['date'];
		$combo_full_name->SelectedData = $row['full_name'];
		$combo_class->SelectedData = $row['class'];
		$combo_term->SelectedData = $row['term'];
		$combo_fees_code->SelectedData = $row['fees_code'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_full_name->SelectedData = $filterer_full_name;
		$combo_class->SelectedData = $filterer_class;
		$combo_term->SelectedText = (isset($filterField[1]) && $filterField[1] == '5' && $filterOperator[1] == '<=>' ? $filterValue[1] : '');
		$combo_fees_code->SelectedData = $filterer_fees_code;
	}
	$combo_full_name->HTML = '<span id="full_name-container' . $rnd1 . '"></span><input type="hidden" name="full_name" id="full_name' . $rnd1 . '" value="' . html_attr($combo_full_name->SelectedData) . '">';
	$combo_full_name->MatchText = '<span id="full_name-container-readonly' . $rnd1 . '"></span><input type="hidden" name="full_name" id="full_name' . $rnd1 . '" value="' . html_attr($combo_full_name->SelectedData) . '">';
	$combo_class->HTML = '<span id="class-container' . $rnd1 . '"></span><input type="hidden" name="class" id="class' . $rnd1 . '" value="' . html_attr($combo_class->SelectedData) . '">';
	$combo_class->MatchText = '<span id="class-container-readonly' . $rnd1 . '"></span><input type="hidden" name="class" id="class' . $rnd1 . '" value="' . html_attr($combo_class->SelectedData) . '">';
	$combo_term->Render();
	$combo_fees_code->HTML = '<span id="fees_code-container' . $rnd1 . '"></span><input type="hidden" name="fees_code" id="fees_code' . $rnd1 . '" value="' . html_attr($combo_fees_code->SelectedData) . '">';
	$combo_fees_code->MatchText = '<span id="fees_code-container-readonly' . $rnd1 . '"></span><input type="hidden" name="fees_code" id="fees_code' . $rnd1 . '" value="' . html_attr($combo_fees_code->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_full_name__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['full_name'] : htmlspecialchars($filterer_full_name, ENT_QUOTES)); ?>"};
		AppGini.current_class__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['class'] : htmlspecialchars($filterer_class, ENT_QUOTES)); ?>"};
		AppGini.current_fees_code__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['fees_code'] : htmlspecialchars($filterer_fees_code, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(full_name_reload__RAND__) == 'function') full_name_reload__RAND__();
				if(typeof(class_reload__RAND__) == 'function') class_reload__RAND__();
				if(typeof(fees_code_reload__RAND__) == 'function') fees_code_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function full_name_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#full_name-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_full_name__RAND__.value, t: 'enrollment', f: 'full_name' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="full_name"]').val(resp.results[0].id);
							$j('[id=full_name-container-readonly__RAND__]').html('<span class="match-text" id="full_name-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=registration_view_parent]').hide(); } else { $j('.btn[id=registration_view_parent]').show(); }


							if(typeof(full_name_update_autofills__RAND__) == 'function') full_name_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'enrollment', f: 'full_name' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_full_name__RAND__.value = e.added.id;
				AppGini.current_full_name__RAND__.text = e.added.text;
				$j('[name="full_name"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=registration_view_parent]').hide(); } else { $j('.btn[id=registration_view_parent]').show(); }


				if(typeof(full_name_update_autofills__RAND__) == 'function') full_name_update_autofills__RAND__();
			});

			if(!$j("#full_name-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_full_name__RAND__.value, t: 'enrollment', f: 'full_name' },
					success: function(resp) {
						$j('[name="full_name"]').val(resp.results[0].id);
						$j('[id=full_name-container-readonly__RAND__]').html('<span class="match-text" id="full_name-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=registration_view_parent]').hide(); } else { $j('.btn[id=registration_view_parent]').show(); }

						if(typeof(full_name_update_autofills__RAND__) == 'function') full_name_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_full_name__RAND__.value, t: 'enrollment', f: 'full_name' },
				success: function(resp) {
					$j('[id=full_name-container__RAND__], [id=full_name-container-readonly__RAND__]').html('<span class="match-text" id="full_name-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=registration_view_parent]').hide(); } else { $j('.btn[id=registration_view_parent]').show(); }

					if(typeof(full_name_update_autofills__RAND__) == 'function') full_name_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function class_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#class-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_class__RAND__.value, t: 'enrollment', f: 'class' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="class"]').val(resp.results[0].id);
							$j('[id=class-container-readonly__RAND__]').html('<span class="match-text" id="class-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=classes_view_parent]').hide(); } else { $j('.btn[id=classes_view_parent]').show(); }


							if(typeof(class_update_autofills__RAND__) == 'function') class_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'enrollment', f: 'class' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_class__RAND__.value = e.added.id;
				AppGini.current_class__RAND__.text = e.added.text;
				$j('[name="class"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=classes_view_parent]').hide(); } else { $j('.btn[id=classes_view_parent]').show(); }


				if(typeof(class_update_autofills__RAND__) == 'function') class_update_autofills__RAND__();
			});

			if(!$j("#class-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_class__RAND__.value, t: 'enrollment', f: 'class' },
					success: function(resp) {
						$j('[name="class"]').val(resp.results[0].id);
						$j('[id=class-container-readonly__RAND__]').html('<span class="match-text" id="class-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=classes_view_parent]').hide(); } else { $j('.btn[id=classes_view_parent]').show(); }

						if(typeof(class_update_autofills__RAND__) == 'function') class_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_class__RAND__.value, t: 'enrollment', f: 'class' },
				success: function(resp) {
					$j('[id=class-container__RAND__], [id=class-container-readonly__RAND__]').html('<span class="match-text" id="class-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=classes_view_parent]').hide(); } else { $j('.btn[id=classes_view_parent]').show(); }

					if(typeof(class_update_autofills__RAND__) == 'function') class_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function fees_code_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#fees_code-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_fees_code__RAND__.value, t: 'enrollment', f: 'fees_code' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="fees_code"]').val(resp.results[0].id);
							$j('[id=fees_code-container-readonly__RAND__]').html('<span class="match-text" id="fees_code-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=fees_structure_view_parent]').hide(); } else { $j('.btn[id=fees_structure_view_parent]').show(); }


							if(typeof(fees_code_update_autofills__RAND__) == 'function') fees_code_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'enrollment', f: 'fees_code' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_fees_code__RAND__.value = e.added.id;
				AppGini.current_fees_code__RAND__.text = e.added.text;
				$j('[name="fees_code"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=fees_structure_view_parent]').hide(); } else { $j('.btn[id=fees_structure_view_parent]').show(); }


				if(typeof(fees_code_update_autofills__RAND__) == 'function') fees_code_update_autofills__RAND__();
			});

			if(!$j("#fees_code-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_fees_code__RAND__.value, t: 'enrollment', f: 'fees_code' },
					success: function(resp) {
						$j('[name="fees_code"]').val(resp.results[0].id);
						$j('[id=fees_code-container-readonly__RAND__]').html('<span class="match-text" id="fees_code-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=fees_structure_view_parent]').hide(); } else { $j('.btn[id=fees_structure_view_parent]').show(); }

						if(typeof(fees_code_update_autofills__RAND__) == 'function') fees_code_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_fees_code__RAND__.value, t: 'enrollment', f: 'fees_code' },
				success: function(resp) {
					$j('[id=fees_code-container__RAND__], [id=fees_code-container-readonly__RAND__]').html('<span class="match-text" id="fees_code-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=fees_structure_view_parent]').hide(); } else { $j('.btn[id=fees_structure_view_parent]').show(); }

					if(typeof(fees_code_update_autofills__RAND__) == 'function') fees_code_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/enrollment_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/enrollment_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return enrollment_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return enrollment_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return enrollment_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#dateDay, #dateMonth, #dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#full_name').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#full_name_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#class').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#class_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('input[name=term]').parent().html('<div class=\"form-control-static\">' + jQuery('input[name=term]:checked').next().text() + '</div>')\n";
		$jsReadOnly .= "\tjQuery('#fees_code').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#fees_code_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace(
		'<%%COMBO(date)%%>', 
		($selected_id && !$arrPerm['edit'] && ($noSaveAsCopy || !$arrPerm['insert']) ? 
			'<div class="form-control-static">' . $combo_date->GetHTML(true) . '</div>' : 
			$combo_date->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(date)%%>', $combo_date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(full_name)%%>', $combo_full_name->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(full_name)%%>', $combo_full_name->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(full_name)%%>', urlencode($combo_full_name->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(class)%%>', $combo_class->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(class)%%>', $combo_class->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(class)%%>', urlencode($combo_class->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(term)%%>', $combo_term->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(term)%%>', $combo_term->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(fees_code)%%>', $combo_fees_code->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fees_code)%%>', $combo_fees_code->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(fees_code)%%>', urlencode($combo_fees_code->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['full_name' => ['registration', 'Full name'], 'class' => ['classes', 'Class'], 'fees_code' => ['fees_structure', 'Fees code'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(stid)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(full_name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(class)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(term)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fees_code)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(amount_received)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(balance)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(cleared)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(structure)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		$templateCode = str_replace('<%%VALUE(date)%%>', app_datetime($row['date']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode(app_datetime($urow['date'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(stid)%%>', safe_html($urow['stid']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(stid)%%>', urlencode($urow['stid']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(full_name)%%>', safe_html($urow['full_name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(full_name)%%>', html_attr($row['full_name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(full_name)%%>', urlencode($urow['full_name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(class)%%>', safe_html($urow['class']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(class)%%>', html_attr($row['class']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(class)%%>', urlencode($urow['class']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(term)%%>', safe_html($urow['term']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(term)%%>', html_attr($row['term']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(term)%%>', urlencode($urow['term']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(fees_code)%%>', safe_html($urow['fees_code']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(fees_code)%%>', html_attr($row['fees_code']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fees_code)%%>', urlencode($urow['fees_code']), $templateCode);
		$templateCode = str_replace('<%%VALUE(amount_received)%%>', safe_html($urow['amount_received']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(amount_received)%%>', urlencode($urow['amount_received']), $templateCode);
		$templateCode = str_replace('<%%VALUE(balance)%%>', safe_html($urow['balance']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(balance)%%>', urlencode($urow['balance']), $templateCode);
		$templateCode = str_replace('<%%CHECKED(cleared)%%>', ($row['cleared'] ? "checked" : ""), $templateCode);
		$templateCode = str_replace('<%%VALUE(structure)%%>', safe_html($urow['structure']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(structure)%%>', urlencode($urow['structure']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(date)%%>', '1', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode('1'), $templateCode);
		$templateCode = str_replace('<%%VALUE(stid)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(stid)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(full_name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(full_name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(class)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(class)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(term)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(term)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fees_code)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fees_code)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(amount_received)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(amount_received)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(balance)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(balance)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%CHECKED(cleared)%%>', '', $templateCode);
		$templateCode = str_replace('<%%VALUE(structure)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(structure)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tclass_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'enrollment_autofill.php?rnd1=$rnd1&mfk=class&id=' + encodeURIComponent('".addslashes($row['class'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'enrollment_autofill.php?rnd1=$rnd1&mfk=class&id=' + encodeURIComponent(AppGini.current_class{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#class$rnd1').prop('disabled', true); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm['insert'] || (($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3)) ? "\$j('#class$rnd1').prop('disabled', false); " : "\$j('#class$rnd1').prop('disabled', true); ")." \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#class_caption').length) \$j('#class_caption').click(function() { class_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('enrollment');
	if($selected_id) {
		$jdata = get_joined_record('enrollment', $selected_id);
		if($jdata === false) $jdata = get_defaults('enrollment');
		$rdata = $row;
	}
	$templateCode .= loadView('enrollment-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: enrollment_dv
	if(function_exists('enrollment_dv')) {
		$args = [];
		enrollment_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}