<?php
// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/enrollment.php');
	include_once(__DIR__ . '/enrollment_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('enrollment');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'enrollment';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`enrollment`.`stid`" => "stid",
		"IF(    CHAR_LENGTH(`registration1`.`full_name`), CONCAT_WS('',   `registration1`.`full_name`), '') /* Full name */" => "full_name",
		"IF(    CHAR_LENGTH(`classes1`.`class`), CONCAT_WS('',   `classes1`.`class`), '') /* Class */" => "class",
		"IF(    CHAR_LENGTH(`classes1`.`year`), CONCAT_WS('',   `classes1`.`year`), '') /* Year */" => "year",
		"`enrollment`.`term`" => "term",
		"`enrollment`.`total_fees`" => "total_fees",
		"`enrollment`.`amount_received`" => "amount_received",
		"`enrollment`.`balance`" => "balance",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`enrollment`.`stid`',
		2 => '`registration1`.`full_name`',
		3 => '`classes1`.`class`',
		4 => '`classes1`.`year`',
		5 => 5,
		6 => '`enrollment`.`total_fees`',
		7 => '`enrollment`.`amount_received`',
		8 => '`enrollment`.`balance`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`enrollment`.`stid`" => "stid",
		"IF(    CHAR_LENGTH(`registration1`.`full_name`), CONCAT_WS('',   `registration1`.`full_name`), '') /* Full name */" => "full_name",
		"IF(    CHAR_LENGTH(`classes1`.`class`), CONCAT_WS('',   `classes1`.`class`), '') /* Class */" => "class",
		"IF(    CHAR_LENGTH(`classes1`.`year`), CONCAT_WS('',   `classes1`.`year`), '') /* Year */" => "year",
		"`enrollment`.`term`" => "term",
		"`enrollment`.`total_fees`" => "total_fees",
		"`enrollment`.`amount_received`" => "amount_received",
		"`enrollment`.`balance`" => "balance",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`enrollment`.`stid`" => "StID",
		"IF(    CHAR_LENGTH(`registration1`.`full_name`), CONCAT_WS('',   `registration1`.`full_name`), '') /* Full name */" => "Full name",
		"IF(    CHAR_LENGTH(`classes1`.`class`), CONCAT_WS('',   `classes1`.`class`), '') /* Class */" => "Class",
		"IF(    CHAR_LENGTH(`classes1`.`year`), CONCAT_WS('',   `classes1`.`year`), '') /* Year */" => "Year",
		"`enrollment`.`term`" => "Term",
		"`enrollment`.`total_fees`" => "Total fees",
		"`enrollment`.`amount_received`" => "Amount received",
		"`enrollment`.`balance`" => "Balance",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`enrollment`.`stid`" => "stid",
		"IF(    CHAR_LENGTH(`registration1`.`full_name`), CONCAT_WS('',   `registration1`.`full_name`), '') /* Full name */" => "full_name",
		"IF(    CHAR_LENGTH(`classes1`.`class`), CONCAT_WS('',   `classes1`.`class`), '') /* Class */" => "class",
		"IF(    CHAR_LENGTH(`classes1`.`year`), CONCAT_WS('',   `classes1`.`year`), '') /* Year */" => "year",
		"`enrollment`.`term`" => "term",
		"`enrollment`.`total_fees`" => "total_fees",
		"`enrollment`.`amount_received`" => "amount_received",
		"`enrollment`.`balance`" => "balance",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['full_name' => 'Full name', 'class' => 'Class', ];

	$x->QueryFrom = "`enrollment` LEFT JOIN `registration` as registration1 ON `registration1`.`id`=`enrollment`.`full_name` LEFT JOIN `classes` as classes1 ON `classes1`.`id`=`enrollment`.`class` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'enrollment_view.php';
	$x->TableTitle = 'Enrolled';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`enrollment`.`stid`';

	$x->ColWidth = [150, 150, 150, 150, 80, 150, 150, ];
	$x->ColCaption = ['Full name', 'Class', 'Year', 'Term', 'Total fees', 'Amount received', 'Balance', ];
	$x->ColFieldName = ['full_name', 'class', 'year', 'term', 'total_fees', 'amount_received', 'balance', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/enrollment_templateTV.html';
	$x->SelectedTemplate = 'templates/enrollment_templateTVS.html';
	$x->TemplateDV = 'templates/enrollment_templateDV.html';
	$x->TemplateDVP = 'templates/enrollment_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: enrollment_init
	$render = true;
	if(function_exists('enrollment_init')) {
		$args = [];
		$render = enrollment_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: enrollment_header
	$headerCode = '';
	if(function_exists('enrollment_header')) {
		$args = [];
		$headerCode = enrollment_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: enrollment_footer
	$footerCode = '';
	if(function_exists('enrollment_footer')) {
		$args = [];
		$footerCode = enrollment_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
