<?php

// Data functions (insert, update, delete, form) for table exams

// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

function exams_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('exams');
	if(!$arrPerm['insert']) return false;

	$data = [
		'class' => Request::lookup('class', ''),
		'total_marks' => Request::val('total_marks', ''),
		'teacher' => Request::val('teacher', ''),
		'subject' => Request::lookup('subject', ''),
		'date' => Request::dateComponents('date', '1'),
	];


	// hook: exams_before_insert
	if(function_exists('exams_before_insert')) {
		$args = [];
		if(!exams_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('exams', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('exams', $recID, calculated_fields()['exams']);

	// hook: exams_after_insert
	if(function_exists('exams_after_insert')) {
		$res = sql("SELECT * FROM `exams` WHERE `exm_id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!exams_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('exams', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) exams_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function exams_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function exams_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('exams', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: exams_before_delete
	if(function_exists('exams_before_delete')) {
		$args = [];
		if(!exams_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: rizalts
	$res = sql("SELECT `exm_id` FROM `exams` WHERE `exm_id`='{$selected_id}'", $eo);
	$exm_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `rizalts` WHERE `exm_id`='" . makeSafe($exm_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'rizalts', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'rizalts', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'exams_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'exams_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `exams` WHERE `exm_id`='{$selected_id}'", $eo);

	// hook: exams_after_delete
	if(function_exists('exams_after_delete')) {
		$args = [];
		exams_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='exams' AND `pkValue`='{$selected_id}'", $eo);
}

function exams_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('exams', $selected_id, 'edit')) return false;

	$data = [
		'class' => Request::lookup('class', ''),
		'total_marks' => Request::val('total_marks', ''),
		'teacher' => Request::val('teacher', ''),
		'subject' => Request::lookup('subject', ''),
		'date' => Request::dateComponents('date', ''),
	];

	// get existing values
	$old_data = getRecord('exams', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: exams_before_update
	if(function_exists('exams_before_update')) {
		$args = ['old_data' => $old_data];
		if(!exams_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'exams', 
		backtick_keys_once($set), 
		['`exm_id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="exams_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('exams', $data['selectedID'], calculated_fields()['exams']);

	// hook: exams_after_update
	if(function_exists('exams_after_update')) {
		$res = sql("SELECT * FROM `exams` WHERE `exm_id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['exm_id'];
		$args = ['old_data' => $old_data];
		if(!exams_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='exams' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function exams_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('exams');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_class = Request::val('filterer_class');
	$filterer_subject = Request::val('filterer_subject');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: class
	$combo_class = new DataCombo;
	// combobox: subject
	$combo_subject = new DataCombo;
	// combobox: date
	$combo_date = new DateCombo;
	$combo_date->DateFormat = "mdy";
	$combo_date->MinYear = defined('exams.date.MinYear') ? constant('exams.date.MinYear') : 1900;
	$combo_date->MaxYear = defined('exams.date.MaxYear') ? constant('exams.date.MaxYear') : 2100;
	$combo_date->DefaultDate = parseMySQLDate('1', '1');
	$combo_date->MonthNames = $Translation['month names'];
	$combo_date->NamePrefix = 'date';

	if($selected_id) {
		if(!check_record_permission('exams', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('exams', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('exams', $selected_id, 'delete');

		$res = sql("SELECT * FROM `exams` WHERE `exm_id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'exams_view.php', false);
		}
		$combo_class->SelectedData = $row['class'];
		$combo_subject->SelectedData = $row['subject'];
		$combo_date->DefaultDate = $row['date'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_class->SelectedData = $filterer_class;
		$combo_subject->SelectedData = $filterer_subject;
	}
	$combo_class->HTML = '<span id="class-container' . $rnd1 . '"></span><input type="hidden" name="class" id="class' . $rnd1 . '" value="' . html_attr($combo_class->SelectedData) . '">';
	$combo_class->MatchText = '<span id="class-container-readonly' . $rnd1 . '"></span><input type="hidden" name="class" id="class' . $rnd1 . '" value="' . html_attr($combo_class->SelectedData) . '">';
	$combo_subject->HTML = '<span id="subject-container' . $rnd1 . '"></span><input type="hidden" name="subject" id="subject' . $rnd1 . '" value="' . html_attr($combo_subject->SelectedData) . '">';
	$combo_subject->MatchText = '<span id="subject-container-readonly' . $rnd1 . '"></span><input type="hidden" name="subject" id="subject' . $rnd1 . '" value="' . html_attr($combo_subject->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_class__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['class'] : htmlspecialchars($filterer_class, ENT_QUOTES)); ?>"};
		AppGini.current_subject__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['subject'] : htmlspecialchars($filterer_subject, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(class_reload__RAND__) == 'function') class_reload__RAND__();
				if(typeof(subject_reload__RAND__) == 'function') subject_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function class_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#class-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_class__RAND__.value, t: 'exams', f: 'class' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="class"]').val(resp.results[0].id);
							$j('[id=class-container-readonly__RAND__]').html('<span class="match-text" id="class-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=enrollment_view_parent]').hide(); } else { $j('.btn[id=enrollment_view_parent]').show(); }


							if(typeof(class_update_autofills__RAND__) == 'function') class_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'exams', f: 'class' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_class__RAND__.value = e.added.id;
				AppGini.current_class__RAND__.text = e.added.text;
				$j('[name="class"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=enrollment_view_parent]').hide(); } else { $j('.btn[id=enrollment_view_parent]').show(); }


				if(typeof(class_update_autofills__RAND__) == 'function') class_update_autofills__RAND__();
			});

			if(!$j("#class-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_class__RAND__.value, t: 'exams', f: 'class' },
					success: function(resp) {
						$j('[name="class"]').val(resp.results[0].id);
						$j('[id=class-container-readonly__RAND__]').html('<span class="match-text" id="class-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=enrollment_view_parent]').hide(); } else { $j('.btn[id=enrollment_view_parent]').show(); }

						if(typeof(class_update_autofills__RAND__) == 'function') class_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_class__RAND__.value, t: 'exams', f: 'class' },
				success: function(resp) {
					$j('[id=class-container__RAND__], [id=class-container-readonly__RAND__]').html('<span class="match-text" id="class-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=enrollment_view_parent]').hide(); } else { $j('.btn[id=enrollment_view_parent]').show(); }

					if(typeof(class_update_autofills__RAND__) == 'function') class_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function subject_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#subject-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_subject__RAND__.value, t: 'exams', f: 'subject' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="subject"]').val(resp.results[0].id);
							$j('[id=subject-container-readonly__RAND__]').html('<span class="match-text" id="subject-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=subjects_view_parent]').hide(); } else { $j('.btn[id=subjects_view_parent]').show(); }


							if(typeof(subject_update_autofills__RAND__) == 'function') subject_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'exams', f: 'subject' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_subject__RAND__.value = e.added.id;
				AppGini.current_subject__RAND__.text = e.added.text;
				$j('[name="subject"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=subjects_view_parent]').hide(); } else { $j('.btn[id=subjects_view_parent]').show(); }


				if(typeof(subject_update_autofills__RAND__) == 'function') subject_update_autofills__RAND__();
			});

			if(!$j("#subject-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_subject__RAND__.value, t: 'exams', f: 'subject' },
					success: function(resp) {
						$j('[name="subject"]').val(resp.results[0].id);
						$j('[id=subject-container-readonly__RAND__]').html('<span class="match-text" id="subject-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=subjects_view_parent]').hide(); } else { $j('.btn[id=subjects_view_parent]').show(); }

						if(typeof(subject_update_autofills__RAND__) == 'function') subject_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_subject__RAND__.value, t: 'exams', f: 'subject' },
				success: function(resp) {
					$j('[id=subject-container__RAND__], [id=subject-container-readonly__RAND__]').html('<span class="match-text" id="subject-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=subjects_view_parent]').hide(); } else { $j('.btn[id=subjects_view_parent]').show(); }

					if(typeof(subject_update_autofills__RAND__) == 'function') subject_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/exams_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/exams_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Exam details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return exams_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return exams_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return exams_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#class').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#class_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#total_marks').replaceWith('<div class=\"form-control-static\" id=\"total_marks\">' + (jQuery('#total_marks').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#teacher').replaceWith('<div class=\"form-control-static\" id=\"teacher\">' + (jQuery('#teacher').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#subject').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#subject_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#dateDay, #dateMonth, #dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(class)%%>', $combo_class->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(class)%%>', $combo_class->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(class)%%>', urlencode($combo_class->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(subject)%%>', $combo_subject->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(subject)%%>', $combo_subject->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(subject)%%>', urlencode($combo_subject->MatchText), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(date)%%>', 
		($selected_id && !$arrPerm['edit'] && ($noSaveAsCopy || !$arrPerm['insert']) ? 
			'<div class="form-control-static">' . $combo_date->GetHTML(true) . '</div>' : 
			$combo_date->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(date)%%>', $combo_date->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['class' => ['enrollment', 'Class'], 'subject' => ['subjects', 'Subject'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(exm_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(class)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(total_marks)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(teacher)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(subject)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(avg_performance)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(highest_mark)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(lowest_mark)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(date)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(exm_id)%%>', safe_html($urow['exm_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(exm_id)%%>', html_attr($row['exm_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(exm_id)%%>', urlencode($urow['exm_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(class)%%>', safe_html($urow['class']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(class)%%>', html_attr($row['class']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(class)%%>', urlencode($urow['class']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(total_marks)%%>', safe_html($urow['total_marks']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(total_marks)%%>', html_attr($row['total_marks']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(total_marks)%%>', urlencode($urow['total_marks']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(teacher)%%>', safe_html($urow['teacher']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(teacher)%%>', html_attr($row['teacher']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(teacher)%%>', urlencode($urow['teacher']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(subject)%%>', safe_html($urow['subject']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(subject)%%>', html_attr($row['subject']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(subject)%%>', urlencode($urow['subject']), $templateCode);
		$templateCode = str_replace('<%%VALUE(avg_performance)%%>', safe_html($urow['avg_performance']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(avg_performance)%%>', urlencode($urow['avg_performance']), $templateCode);
		$templateCode = str_replace('<%%VALUE(highest_mark)%%>', safe_html($urow['highest_mark']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(highest_mark)%%>', urlencode($urow['highest_mark']), $templateCode);
		$templateCode = str_replace('<%%VALUE(lowest_mark)%%>', safe_html($urow['lowest_mark']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(lowest_mark)%%>', urlencode($urow['lowest_mark']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', app_datetime($row['date']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode(app_datetime($urow['date'])), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(exm_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(exm_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(class)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(class)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(total_marks)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(total_marks)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(teacher)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(teacher)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(subject)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(subject)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(avg_performance)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(avg_performance)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(highest_mark)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(highest_mark)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(lowest_mark)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(lowest_mark)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', '1', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode('1'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('exams');
	if($selected_id) {
		$jdata = get_joined_record('exams', $selected_id);
		if($jdata === false) $jdata = get_defaults('exams');
		$rdata = $row;
	}
	$templateCode .= loadView('exams-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: exams_dv
	if(function_exists('exams_dv')) {
		$args = [];
		exams_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}