<?php
// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/exams.php');
	include_once(__DIR__ . '/exams_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('exams');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'exams';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`exams`.`exm_id`" => "exm_id",
		"IF(    CHAR_LENGTH(`classes1`.`class`) || CHAR_LENGTH(`enrollment1`.`term`), CONCAT_WS('',   `classes1`.`class`, '-', `enrollment1`.`term`), '') /* Class */" => "class",
		"`exams`.`total_marks`" => "total_marks",
		"`exams`.`teacher`" => "teacher",
		"IF(    CHAR_LENGTH(`subjects1`.`subject`), CONCAT_WS('',   `subjects1`.`subject`), '') /* Subject */" => "subject",
		"`exams`.`avg_performance`" => "avg_performance",
		"`exams`.`highest_mark`" => "highest_mark",
		"`exams`.`lowest_mark`" => "lowest_mark",
		"if(`exams`.`date`,date_format(`exams`.`date`,'%m/%d/%Y'),'')" => "date",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`exams`.`exm_id`',
		2 => 2,
		3 => '`exams`.`total_marks`',
		4 => 4,
		5 => '`subjects1`.`subject`',
		6 => '`exams`.`avg_performance`',
		7 => '`exams`.`highest_mark`',
		8 => '`exams`.`lowest_mark`',
		9 => '`exams`.`date`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`exams`.`exm_id`" => "exm_id",
		"IF(    CHAR_LENGTH(`classes1`.`class`) || CHAR_LENGTH(`enrollment1`.`term`), CONCAT_WS('',   `classes1`.`class`, '-', `enrollment1`.`term`), '') /* Class */" => "class",
		"`exams`.`total_marks`" => "total_marks",
		"`exams`.`teacher`" => "teacher",
		"IF(    CHAR_LENGTH(`subjects1`.`subject`), CONCAT_WS('',   `subjects1`.`subject`), '') /* Subject */" => "subject",
		"`exams`.`avg_performance`" => "avg_performance",
		"`exams`.`highest_mark`" => "highest_mark",
		"`exams`.`lowest_mark`" => "lowest_mark",
		"if(`exams`.`date`,date_format(`exams`.`date`,'%m/%d/%Y'),'')" => "date",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`exams`.`exm_id`" => "ID",
		"IF(    CHAR_LENGTH(`classes1`.`class`) || CHAR_LENGTH(`enrollment1`.`term`), CONCAT_WS('',   `classes1`.`class`, '-', `enrollment1`.`term`), '') /* Class */" => "Class",
		"`exams`.`total_marks`" => "Total marks",
		"`exams`.`teacher`" => "Teacher",
		"IF(    CHAR_LENGTH(`subjects1`.`subject`), CONCAT_WS('',   `subjects1`.`subject`), '') /* Subject */" => "Subject",
		"`exams`.`avg_performance`" => "Avg performance",
		"`exams`.`highest_mark`" => "Highest mark",
		"`exams`.`lowest_mark`" => "Lowest mark",
		"`exams`.`date`" => "Date",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`exams`.`exm_id`" => "exm_id",
		"IF(    CHAR_LENGTH(`classes1`.`class`) || CHAR_LENGTH(`enrollment1`.`term`), CONCAT_WS('',   `classes1`.`class`, '-', `enrollment1`.`term`), '') /* Class */" => "class",
		"`exams`.`total_marks`" => "total_marks",
		"`exams`.`teacher`" => "teacher",
		"IF(    CHAR_LENGTH(`subjects1`.`subject`), CONCAT_WS('',   `subjects1`.`subject`), '') /* Subject */" => "subject",
		"`exams`.`avg_performance`" => "avg_performance",
		"`exams`.`highest_mark`" => "highest_mark",
		"`exams`.`lowest_mark`" => "lowest_mark",
		"if(`exams`.`date`,date_format(`exams`.`date`,'%m/%d/%Y'),'')" => "date",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['class' => 'Class', 'subject' => 'Subject', ];

	$x->QueryFrom = "`exams` LEFT JOIN `enrollment` as enrollment1 ON `enrollment1`.`stid`=`exams`.`class` LEFT JOIN `classes` as classes1 ON `classes1`.`id`=`enrollment1`.`class` LEFT JOIN `subjects` as subjects1 ON `subjects1`.`sub_id`=`exams`.`subject` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'exams_view.php';
	$x->TableTitle = 'Exams';
	$x->TableIcon = 'resources/table_icons/ask_and_answer.png';
	$x->PrimaryKey = '`exams`.`exm_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Class', 'Total marks', 'Teacher', 'Subject', 'Avg performance', 'Highest mark', 'Lowest mark', 'Date', ];
	$x->ColFieldName = ['class', 'total_marks', 'teacher', 'subject', 'avg_performance', 'highest_mark', 'lowest_mark', 'date', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/exams_templateTV.html';
	$x->SelectedTemplate = 'templates/exams_templateTVS.html';
	$x->TemplateDV = 'templates/exams_templateDV.html';
	$x->TemplateDVP = 'templates/exams_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: exams_init
	$render = true;
	if(function_exists('exams_init')) {
		$args = [];
		$render = exams_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: exams_header
	$headerCode = '';
	if(function_exists('exams_header')) {
		$args = [];
		$headerCode = exams_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: exams_footer
	$footerCode = '';
	if(function_exists('exams_footer')) {
		$args = [];
		$footerCode = exams_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
