<?php
// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/fees_structure.php');
	include_once(__DIR__ . '/fees_structure_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('fees_structure');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'fees_structure';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`fees_structure`.`id`" => "id",
		"`fees_structure`.`code`" => "code",
		"`fees_structure`.`fees`" => "fees",
		"`fees_structure`.`description`" => "description",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`fees_structure`.`id`',
		2 => 2,
		3 => '`fees_structure`.`fees`',
		4 => 4,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`fees_structure`.`id`" => "id",
		"`fees_structure`.`code`" => "code",
		"`fees_structure`.`fees`" => "fees",
		"`fees_structure`.`description`" => "description",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`fees_structure`.`id`" => "ID",
		"`fees_structure`.`code`" => "Code",
		"`fees_structure`.`fees`" => "Fees",
		"`fees_structure`.`description`" => "Description",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`fees_structure`.`id`" => "id",
		"`fees_structure`.`code`" => "code",
		"`fees_structure`.`fees`" => "fees",
		"`fees_structure`.`description`" => "description",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`fees_structure` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'fees_structure_view.php';
	$x->TableTitle = 'Fees structure and Activities';
	$x->TableIcon = 'resources/table_icons/balance.png';
	$x->PrimaryKey = '`fees_structure`.`id`';

	$x->ColWidth = [150, 80, 150, ];
	$x->ColCaption = ['Code', 'Fees', 'Description', ];
	$x->ColFieldName = ['code', 'fees', 'description', ];
	$x->ColNumber  = [2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/fees_structure_templateTV.html';
	$x->SelectedTemplate = 'templates/fees_structure_templateTVS.html';
	$x->TemplateDV = 'templates/fees_structure_templateDV.html';
	$x->TemplateDVP = 'templates/fees_structure_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "col-lg-4";
	$x->DVClasses = "col-lg-8";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: fees_structure_init
	$render = true;
	if(function_exists('fees_structure_init')) {
		$args = [];
		$render = fees_structure_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: fees_structure_header
	$headerCode = '';
	if(function_exists('fees_structure_header')) {
		$args = [];
		$headerCode = fees_structure_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: fees_structure_footer
	$footerCode = '';
	if(function_exists('fees_structure_footer')) {
		$args = [];
		$footerCode = fees_structure_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
