<?php
// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/fees_payments.php');
	include_once(__DIR__ . '/fees_payments_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('fees_payments');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'fees_payments';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`fees_payments`.`id`" => "id",
		"if(`fees_payments`.`date`,date_format(`fees_payments`.`date`,'%m/%d/%Y'),'')" => "date",
		"IF(    CHAR_LENGTH(`registration1`.`full_name`), CONCAT_WS('',   `registration1`.`full_name`), '') /* Student name */" => "student",
		"IF(    CHAR_LENGTH(`classes1`.`class`), CONCAT_WS('',   `classes1`.`class`), '') /* Class */" => "class",
		"IF(    CHAR_LENGTH(`enrollment1`.`term`), CONCAT_WS('',   `enrollment1`.`term`), '') /* Term */" => "term",
		"`fees_payments`.`amount_received`" => "amount_received",
		"`fees_payments`.`received_from`" => "received_from",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`fees_payments`.`id`',
		2 => '`fees_payments`.`date`',
		3 => 3,
		4 => 4,
		5 => '`enrollment1`.`term`',
		6 => '`fees_payments`.`amount_received`',
		7 => 7,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`fees_payments`.`id`" => "id",
		"if(`fees_payments`.`date`,date_format(`fees_payments`.`date`,'%m/%d/%Y'),'')" => "date",
		"IF(    CHAR_LENGTH(`registration1`.`full_name`), CONCAT_WS('',   `registration1`.`full_name`), '') /* Student name */" => "student",
		"IF(    CHAR_LENGTH(`classes1`.`class`), CONCAT_WS('',   `classes1`.`class`), '') /* Class */" => "class",
		"IF(    CHAR_LENGTH(`enrollment1`.`term`), CONCAT_WS('',   `enrollment1`.`term`), '') /* Term */" => "term",
		"`fees_payments`.`amount_received`" => "amount_received",
		"`fees_payments`.`received_from`" => "received_from",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`fees_payments`.`id`" => "ID",
		"`fees_payments`.`date`" => "Date",
		"IF(    CHAR_LENGTH(`registration1`.`full_name`), CONCAT_WS('',   `registration1`.`full_name`), '') /* Student name */" => "Student name",
		"IF(    CHAR_LENGTH(`classes1`.`class`), CONCAT_WS('',   `classes1`.`class`), '') /* Class */" => "Class",
		"IF(    CHAR_LENGTH(`enrollment1`.`term`), CONCAT_WS('',   `enrollment1`.`term`), '') /* Term */" => "Term",
		"`fees_payments`.`amount_received`" => "Amount received",
		"`fees_payments`.`received_from`" => "Received from",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`fees_payments`.`id`" => "id",
		"if(`fees_payments`.`date`,date_format(`fees_payments`.`date`,'%m/%d/%Y'),'')" => "date",
		"IF(    CHAR_LENGTH(`registration1`.`full_name`), CONCAT_WS('',   `registration1`.`full_name`), '') /* Student name */" => "student",
		"IF(    CHAR_LENGTH(`classes1`.`class`), CONCAT_WS('',   `classes1`.`class`), '') /* Class */" => "class",
		"IF(    CHAR_LENGTH(`enrollment1`.`term`), CONCAT_WS('',   `enrollment1`.`term`), '') /* Term */" => "term",
		"`fees_payments`.`amount_received`" => "amount_received",
		"`fees_payments`.`received_from`" => "received_from",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['student' => 'Student name', ];

	$x->QueryFrom = "`fees_payments` LEFT JOIN `enrollment` as enrollment1 ON `enrollment1`.`stid`=`fees_payments`.`student` LEFT JOIN `registration` as registration1 ON `registration1`.`id`=`enrollment1`.`full_name` LEFT JOIN `classes` as classes1 ON `classes1`.`id`=`enrollment1`.`class` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'fees_payments_view.php';
	$x->TableTitle = 'Payments';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`fees_payments`.`id`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Date', 'Student name', 'Amount received', 'Received from', ];
	$x->ColFieldName = ['date', 'student', 'amount_received', 'received_from', ];
	$x->ColNumber  = [2, 3, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/fees_payments_templateTV.html';
	$x->SelectedTemplate = 'templates/fees_payments_templateTVS.html';
	$x->TemplateDV = 'templates/fees_payments_templateDV.html';
	$x->TemplateDVP = 'templates/fees_payments_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: fees_payments_init
	$render = true;
	if(function_exists('fees_payments_init')) {
		$args = [];
		$render = fees_payments_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: fees_payments_header
	$headerCode = '';
	if(function_exists('fees_payments_header')) {
		$args = [];
		$headerCode = fees_payments_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: fees_payments_footer
	$footerCode = '';
	if(function_exists('fees_payments_footer')) {
		$args = [];
		$footerCode = fees_payments_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
