<?php
// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');

	handle_maintenance();

	header('Content-type: text/javascript; charset=' . datalist_db_encoding);

	$table_perms = getTablePermissions('fees_payments');
	if(!$table_perms['access']) die('// Access denied!');

	$mfk = Request::val('mfk');
	$id = makeSafe(Request::val('id'));
	$rnd1 = intval(Request::val('rnd1')); if(!$rnd1) $rnd1 = '';

	if(!$mfk) {
		die('// No js code available!');
	}

	switch($mfk) {

		case 'student':
			if(!$id) {
				?>
				$j('#class<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#term<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT if(`enrollment`.`date`,date_format(`enrollment`.`date`,'%m/%d/%Y'),'') as 'date', `enrollment`.`stid` as 'stid', IF(    CHAR_LENGTH(`registration1`.`full_name`), CONCAT_WS('',   `registration1`.`full_name`), '') as 'full_name', IF(    CHAR_LENGTH(`classes1`.`class`), CONCAT_WS('',   `classes1`.`class`), '') as 'class', `enrollment`.`term` as 'term', IF(    CHAR_LENGTH(`classes1`.`year`), CONCAT_WS('',   `classes1`.`year`), '') as 'year', IF(    CHAR_LENGTH(`fees_structure1`.`code`) || CHAR_LENGTH(`fees_structure1`.`fees`), CONCAT_WS('',   `fees_structure1`.`code`, '/', `fees_structure1`.`fees`), '') as 'fees_code', `enrollment`.`amount_received` as 'amount_received', `enrollment`.`balance` as 'balance', concat('<i class=\"glyphicon glyphicon-', if(`enrollment`.`cleared`, 'check', 'unchecked'), '\"></i>') as 'cleared', `enrollment`.`structure` as 'structure' FROM `enrollment` LEFT JOIN `registration` as registration1 ON `registration1`.`id`=`enrollment`.`full_name` LEFT JOIN `classes` as classes1 ON `classes1`.`id`=`enrollment`.`class` LEFT JOIN `fees_structure` as fees_structure1 ON `fees_structure1`.`id`=`enrollment`.`fees_code`  WHERE `enrollment`.`stid`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#class<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['class']))); ?>&nbsp;');
			$j('#term<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['term']))); ?>&nbsp;');
			<?php
			break;


	}

?>