<?php
// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/registration.php');
	include_once(__DIR__ . '/registration_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('registration');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'registration';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`registration`.`id`" => "id",
		"if(`registration`.`date_of_joining`,date_format(`registration`.`date_of_joining`,'%m/%d/%Y'),'')" => "date_of_joining",
		"`registration`.`photo`" => "photo",
		"`registration`.`full_name`" => "full_name",
		"if(`registration`.`date_of_birth`,date_format(`registration`.`date_of_birth`,'%m/%d/%Y'),'')" => "date_of_birth",
		"`registration`.`age`" => "age",
		"`registration`.`gender`" => "gender",
		"`registration`.`parent_gurdian`" => "parent_gurdian",
		"CONCAT_WS('-', LEFT(`registration`.`contact`,3), MID(`registration`.`contact`,4,3), RIGHT(`registration`.`contact`,4))" => "contact",
		"`registration`.`address`" => "address",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`registration`.`id`',
		2 => '`registration`.`date_of_joining`',
		3 => 3,
		4 => 4,
		5 => '`registration`.`date_of_birth`',
		6 => '`registration`.`age`',
		7 => 7,
		8 => 8,
		9 => '`registration`.`contact`',
		10 => 10,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`registration`.`id`" => "id",
		"if(`registration`.`date_of_joining`,date_format(`registration`.`date_of_joining`,'%m/%d/%Y'),'')" => "date_of_joining",
		"`registration`.`photo`" => "photo",
		"`registration`.`full_name`" => "full_name",
		"if(`registration`.`date_of_birth`,date_format(`registration`.`date_of_birth`,'%m/%d/%Y'),'')" => "date_of_birth",
		"`registration`.`age`" => "age",
		"`registration`.`gender`" => "gender",
		"`registration`.`parent_gurdian`" => "parent_gurdian",
		"CONCAT_WS('-', LEFT(`registration`.`contact`,3), MID(`registration`.`contact`,4,3), RIGHT(`registration`.`contact`,4))" => "contact",
		"`registration`.`address`" => "address",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`registration`.`id`" => "ID",
		"`registration`.`date_of_joining`" => "Date of joining",
		"`registration`.`full_name`" => "Full name",
		"`registration`.`date_of_birth`" => "Date of birth",
		"`registration`.`age`" => "Age",
		"`registration`.`gender`" => "Gender",
		"`registration`.`parent_gurdian`" => "Parent /Gurdian",
		"`registration`.`contact`" => "Contact",
		"`registration`.`address`" => "Address/Residence",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`registration`.`id`" => "id",
		"if(`registration`.`date_of_joining`,date_format(`registration`.`date_of_joining`,'%m/%d/%Y'),'')" => "date_of_joining",
		"`registration`.`full_name`" => "full_name",
		"if(`registration`.`date_of_birth`,date_format(`registration`.`date_of_birth`,'%m/%d/%Y'),'')" => "date_of_birth",
		"`registration`.`age`" => "age",
		"`registration`.`gender`" => "gender",
		"`registration`.`parent_gurdian`" => "parent_gurdian",
		"CONCAT_WS('-', LEFT(`registration`.`contact`,3), MID(`registration`.`contact`,4,3), RIGHT(`registration`.`contact`,4))" => "contact",
		"`registration`.`address`" => "address",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`registration` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = (getLoggedAdmin() !== false);
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'registration_view.php';
	$x->TableTitle = 'Registration';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`registration`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Date of joining', 'Photo', 'Full name', 'Date of birth', 'Age', 'Gender', ];
	$x->ColFieldName = ['date_of_joining', 'photo', 'full_name', 'date_of_birth', 'age', 'gender', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/registration_templateTV.html';
	$x->SelectedTemplate = 'templates/registration_templateTVS.html';
	$x->TemplateDV = 'templates/registration_templateDV.html';
	$x->TemplateDVP = 'templates/registration_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: registration_init
	$render = true;
	if(function_exists('registration_init')) {
		$args = [];
		$render = registration_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: registration_header
	$headerCode = '';
	if(function_exists('registration_header')) {
		$args = [];
		$headerCode = registration_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: registration_footer
	$footerCode = '';
	if(function_exists('registration_footer')) {
		$args = [];
		$footerCode = registration_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
