<?php
// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/rizalts.php');
	include_once(__DIR__ . '/rizalts_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('rizalts');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'rizalts';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`rizalts`.`id`" => "id",
		"IF(    CHAR_LENGTH(`exams1`.`exm_id`), CONCAT_WS('',   `exams1`.`exm_id`), '') /* Exm id */" => "exm_id",
		"IF(    CHAR_LENGTH(`registration1`.`full_name`), CONCAT_WS('',   `registration1`.`full_name`), '') /* Student name */" => "student_name",
		"IF(    CHAR_LENGTH(`exams1`.`total_marks`), CONCAT_WS('',   `exams1`.`total_marks`), '') /* Total marks */" => "total_marks",
		"`rizalts`.`result`" => "result",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`rizalts`.`id`',
		2 => '`exams1`.`exm_id`',
		3 => 3,
		4 => '`exams1`.`total_marks`',
		5 => '`rizalts`.`result`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`rizalts`.`id`" => "id",
		"IF(    CHAR_LENGTH(`exams1`.`exm_id`), CONCAT_WS('',   `exams1`.`exm_id`), '') /* Exm id */" => "exm_id",
		"IF(    CHAR_LENGTH(`registration1`.`full_name`), CONCAT_WS('',   `registration1`.`full_name`), '') /* Student name */" => "student_name",
		"IF(    CHAR_LENGTH(`exams1`.`total_marks`), CONCAT_WS('',   `exams1`.`total_marks`), '') /* Total marks */" => "total_marks",
		"`rizalts`.`result`" => "result",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`rizalts`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`exams1`.`exm_id`), CONCAT_WS('',   `exams1`.`exm_id`), '') /* Exm id */" => "Exm id",
		"IF(    CHAR_LENGTH(`registration1`.`full_name`), CONCAT_WS('',   `registration1`.`full_name`), '') /* Student name */" => "Student name",
		"IF(    CHAR_LENGTH(`exams1`.`total_marks`), CONCAT_WS('',   `exams1`.`total_marks`), '') /* Total marks */" => "Total marks",
		"`rizalts`.`result`" => "Result",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`rizalts`.`id`" => "id",
		"IF(    CHAR_LENGTH(`exams1`.`exm_id`), CONCAT_WS('',   `exams1`.`exm_id`), '') /* Exm id */" => "exm_id",
		"IF(    CHAR_LENGTH(`registration1`.`full_name`), CONCAT_WS('',   `registration1`.`full_name`), '') /* Student name */" => "student_name",
		"IF(    CHAR_LENGTH(`exams1`.`total_marks`), CONCAT_WS('',   `exams1`.`total_marks`), '') /* Total marks */" => "total_marks",
		"`rizalts`.`result`" => "result",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['exm_id' => 'Exm id', 'student_name' => 'Student name', ];

	$x->QueryFrom = "`rizalts` LEFT JOIN `exams` as exams1 ON `exams1`.`exm_id`=`rizalts`.`exm_id` LEFT JOIN `enrollment` as enrollment1 ON `enrollment1`.`stid`=`rizalts`.`student_name` LEFT JOIN `registration` as registration1 ON `registration1`.`id`=`enrollment1`.`full_name` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'rizalts_view.php';
	$x->TableTitle = 'Results';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`rizalts`.`id`';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['Student name', 'Total marks', 'Result', ];
	$x->ColFieldName = ['student_name', 'total_marks', 'result', ];
	$x->ColNumber  = [3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/rizalts_templateTV.html';
	$x->SelectedTemplate = 'templates/rizalts_templateTVS.html';
	$x->TemplateDV = 'templates/rizalts_templateDV.html';
	$x->TemplateDVP = 'templates/rizalts_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: rizalts_init
	$render = true;
	if(function_exists('rizalts_init')) {
		$args = [];
		$render = rizalts_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: rizalts_header
	$headerCode = '';
	if(function_exists('rizalts_header')) {
		$args = [];
		$headerCode = rizalts_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: rizalts_footer
	$footerCode = '';
	if(function_exists('rizalts_footer')) {
		$args = [];
		$footerCode = rizalts_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
