<?php
// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');

	handle_maintenance();

	header('Content-type: text/javascript; charset=' . datalist_db_encoding);

	$table_perms = getTablePermissions('rizalts');
	if(!$table_perms['access']) die('// Access denied!');

	$mfk = Request::val('mfk');
	$id = makeSafe(Request::val('id'));
	$rnd1 = intval(Request::val('rnd1')); if(!$rnd1) $rnd1 = '';

	if(!$mfk) {
		die('// No js code available!');
	}

	switch($mfk) {

		case 'exm_id':
			if(!$id) {
				?>
				$j('#total_marks<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `exams`.`exm_id` as 'exm_id', IF(    CHAR_LENGTH(`classes1`.`class`) || CHAR_LENGTH(`enrollment1`.`term`), CONCAT_WS('',   `classes1`.`class`, '-', `enrollment1`.`term`), '') as 'class', `exams`.`total_marks` as 'total_marks', `exams`.`teacher` as 'teacher', IF(    CHAR_LENGTH(`subjects1`.`subject`), CONCAT_WS('',   `subjects1`.`subject`), '') as 'subject', `exams`.`avg_performance` as 'avg_performance', `exams`.`highest_mark` as 'highest_mark', `exams`.`lowest_mark` as 'lowest_mark', if(`exams`.`date`,date_format(`exams`.`date`,'%m/%d/%Y'),'') as 'date' FROM `exams` LEFT JOIN `enrollment` as enrollment1 ON `enrollment1`.`stid`=`exams`.`class` LEFT JOIN `classes` as classes1 ON `classes1`.`id`=`enrollment1`.`class` LEFT JOIN `subjects` as subjects1 ON `subjects1`.`sub_id`=`exams`.`subject`  WHERE `exams`.`exm_id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#total_marks<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['total_marks']))); ?>&nbsp;');
			<?php
			break;


	}

?>