<?php
// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/staff.php');
	include_once(__DIR__ . '/staff_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('staff');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'staff';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`staff`.`id`" => "id",
		"`staff`.`staff_id`" => "staff_id",
		"`staff`.`full_name`" => "full_name",
		"`staff`.`contact`" => "contact",
		"IF(    CHAR_LENGTH(`subjects1`.`subject`), CONCAT_WS('',   `subjects1`.`subject`), '') /* Subject */" => "subject",
		"if(`staff`.`date_of_joining`,date_format(`staff`.`date_of_joining`,'%m/%d/%Y'),'')" => "date_of_joining",
		"if(`staff`.`contract_ends`,date_format(`staff`.`contract_ends`,'%m/%d/%Y'),'')" => "contract_ends",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`staff`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`subjects1`.`subject`',
		6 => '`staff`.`date_of_joining`',
		7 => '`staff`.`contract_ends`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`staff`.`id`" => "id",
		"`staff`.`staff_id`" => "staff_id",
		"`staff`.`full_name`" => "full_name",
		"`staff`.`contact`" => "contact",
		"IF(    CHAR_LENGTH(`subjects1`.`subject`), CONCAT_WS('',   `subjects1`.`subject`), '') /* Subject */" => "subject",
		"if(`staff`.`date_of_joining`,date_format(`staff`.`date_of_joining`,'%m/%d/%Y'),'')" => "date_of_joining",
		"if(`staff`.`contract_ends`,date_format(`staff`.`contract_ends`,'%m/%d/%Y'),'')" => "contract_ends",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`staff`.`id`" => "sta_id",
		"`staff`.`staff_id`" => "Staff id",
		"`staff`.`full_name`" => "Full name",
		"`staff`.`contact`" => "Contact",
		"IF(    CHAR_LENGTH(`subjects1`.`subject`), CONCAT_WS('',   `subjects1`.`subject`), '') /* Subject */" => "Subject",
		"`staff`.`date_of_joining`" => "Date of joining",
		"`staff`.`contract_ends`" => "Contract ends",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`staff`.`id`" => "id",
		"`staff`.`staff_id`" => "staff_id",
		"`staff`.`full_name`" => "full_name",
		"`staff`.`contact`" => "contact",
		"IF(    CHAR_LENGTH(`subjects1`.`subject`), CONCAT_WS('',   `subjects1`.`subject`), '') /* Subject */" => "subject",
		"if(`staff`.`date_of_joining`,date_format(`staff`.`date_of_joining`,'%m/%d/%Y'),'')" => "date_of_joining",
		"if(`staff`.`contract_ends`,date_format(`staff`.`contract_ends`,'%m/%d/%Y'),'')" => "contract_ends",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['subject' => 'Subject', ];

	$x->QueryFrom = "`staff` LEFT JOIN `subjects` as subjects1 ON `subjects1`.`sub_id`=`staff`.`subject` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'staff_view.php';
	$x->TableTitle = 'Staff';
	$x->TableIcon = 'resources/table_icons/reseller_programm.png';
	$x->PrimaryKey = '`staff`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Staff id', 'Full name', 'Contact', 'Subject', 'Date of joining', 'Contract ends', ];
	$x->ColFieldName = ['staff_id', 'full_name', 'contact', 'subject', 'date_of_joining', 'contract_ends', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/staff_templateTV.html';
	$x->SelectedTemplate = 'templates/staff_templateTVS.html';
	$x->TemplateDV = 'templates/staff_templateDV.html';
	$x->TemplateDVP = 'templates/staff_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: staff_init
	$render = true;
	if(function_exists('staff_init')) {
		$args = [];
		$render = staff_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: staff_header
	$headerCode = '';
	if(function_exists('staff_header')) {
		$args = [];
		$headerCode = staff_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: staff_footer
	$footerCode = '';
	if(function_exists('staff_footer')) {
		$args = [];
		$footerCode = staff_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
