<?php
// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/subjects.php');
	include_once(__DIR__ . '/subjects_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('subjects');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'subjects';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`subjects`.`sub_id`" => "sub_id",
		"`subjects`.`subject`" => "subject",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`subjects`.`sub_id`',
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`subjects`.`sub_id`" => "sub_id",
		"`subjects`.`subject`" => "subject",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`subjects`.`sub_id`" => "Subject ID",
		"`subjects`.`subject`" => "Subject",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`subjects`.`sub_id`" => "sub_id",
		"`subjects`.`subject`" => "subject",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`subjects` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'subjects_view.php';
	$x->TableTitle = 'Subjects';
	$x->TableIcon = 'resources/table_icons/font_subscript.png';
	$x->PrimaryKey = '`subjects`.`sub_id`';

	$x->ColWidth = [150, ];
	$x->ColCaption = ['Subject', ];
	$x->ColFieldName = ['subject', ];
	$x->ColNumber  = [2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/subjects_templateTV.html';
	$x->SelectedTemplate = 'templates/subjects_templateTVS.html';
	$x->TemplateDV = 'templates/subjects_templateDV.html';
	$x->TemplateDVP = 'templates/subjects_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: subjects_init
	$render = true;
	if(function_exists('subjects_init')) {
		$args = [];
		$render = subjects_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: subjects_header
	$headerCode = '';
	if(function_exists('subjects_header')) {
		$args = [];
		$headerCode = subjects_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: subjects_footer
	$footerCode = '';
	if(function_exists('subjects_footer')) {
		$args = [];
		$footerCode = subjects_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
